services:
  caddy:
    image: ghcr.io/lewsion/caddy-cloudflare:latest # Prebuilt Caddy with Cloudflare DNS plugin
    container_name: caddy-cloudflare
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "2019:2019" # Caddy admin API (optional)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Main Caddy configuration
      - data:/data                 # Caddy data (certificates, etc.)
      - config:/config             # Caddy config (internal state)
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN} # Your Cloudflare API token

volumes:
  data:
  config: