name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'Dockerfile'        # Trigger only if Dockerfile changes
      - 'docker/**'         # Or any files in a docker/ folder
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'        # Trigger only if Dockerfile changes
      - 'docker/**'         # Or any files in a docker/ folder
  workflow_dispatch:

# Permissions for GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5

      # Step 2: Set lowercase repository and owner names for Docker tags
      - name: Set lowercase repository and owner names
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "OWNER_NAME=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # Step 3: Setup Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Build and push Docker image with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_NAME }}/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.OWNER_NAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
